[project]
name = "fifty-one"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "anywidget>=0.9.18",
    "fiftyone>=1.8.1",
    "fiftyone-db==1.3.0",
    "ipywidgets>=8.1.7",
    "supervision>=0.26.1",
]
